# Generated by Django 2.2.7 on 2020-03-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200314_0819'),
        ('sale', '0003_auto_20200314_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='store',
        ),
        migrations.AddField(
            model_name='sale',
            name='productstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='product.ProductStock'),
        ),
    ]
