# Generated by Django 3.0.4 on 2020-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_salechilddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
