# Generated by Django 2.2.7 on 2020-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20200722_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
