# Generated by Django 2.2.7 on 2020-04-13 07:51

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=100)),
                ('promotion_detail', models.TextField()),
                ('promotion_img', models.ImageField(blank=True, null=True, upload_to=promotion.models.pro_img)),
            ],
        ),
    ]
