# Generated by Django 3.0.4 on 2020-05-20 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20200427_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='img',
            new_name='promotion_img',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='title',
            new_name='promotion_name',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='user',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
