# Generated by Django 3.0.4 on 2020-05-21 06:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20200520_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_img',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
