# Generated by Django 3.0.4 on 2020-05-21 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20200521_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
