# Generated by Django 3.0.4 on 2020-05-21 07:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_auto_20200521_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
