# Generated by Django 3.0.4 on 2020-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_auto_20200521_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
