# Generated by Django 3.0.4 on 2020-07-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_promotion_promotiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
