# Generated by Django 3.1.1 on 2021-01-19 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICStockHD',
            fields=[
                ('docuid', models.IntegerField(primary_key=True, serialize=False)),
                ('docuno', models.CharField(blank=True, max_length=50, null=True)),
                ('remark1', models.CharField(blank=True, max_length=255, null=True)),
                ('docudate', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ICStockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listno', models.IntegerField()),
                ('goodid', models.IntegerField()),
                ('goodcode', models.CharField(blank=True, max_length=100, null=True)),
                ('goodname', models.CharField(blank=True, max_length=200, null=True)),
                ('goodqty', models.IntegerField(default=0)),
                ('inveid', models.IntegerField(blank=True, null=True)),
                ('invecode', models.CharField(blank=True, max_length=50, null=True)),
                ('invename', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('icstockhd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfer.icstockhd')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listno', 'icstockhd')},
            },
        ),
    ]
