# Generated by Django 2.2.7 on 2020-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='receiving',
            field=models.BooleanField(default=False),
        ),
    ]
