# Generated by Django 2.2.7 on 2020-03-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200314_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='higher_stock',
            field=models.BooleanField(default=False),
        ),
    ]
