# Generated by Django 2.2.7 on 2020-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_higher_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finished_goods',
            field=models.BooleanField(default=False),
        ),
    ]
