# Generated by Django 3.0.4 on 2020-07-22 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200520_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='parents', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Partnumber does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productsubfamily',
            name='name',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='productsubfamily',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
