# Generated by Django 2.2.7 on 2020-03-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_higher_stock'),
        ('receiving', '0003_receiving_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='productstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='product.ProductStock'),
        ),
    ]
