# Generated by Django 3.0.4 on 2020-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_inspection_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
