# Generated by Django 3.1.1 on 2020-12-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receiving', '0005_auto_20200722_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoInvHD',
            fields=[
                ('poinvid', models.IntegerField(primary_key=True, serialize=False)),
                ('docuno', models.CharField(blank=True, max_length=50, null=True)),
                ('totabaseamnt', models.FloatField(default=0)),
                ('vatamnt', models.FloatField(default=0)),
                ('netamnt', models.FloatField(default=0)),
                ('vendorname', models.CharField(blank=True, max_length=250, null=True)),
                ('receivedate', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoInvDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listno', models.IntegerField()),
                ('goodid', models.IntegerField()),
                ('goodcode', models.CharField(blank=True, max_length=100, null=True)),
                ('goodname', models.CharField(blank=True, max_length=200, null=True)),
                ('goodqty', models.IntegerField(default=1)),
                ('goodamnt', models.FloatField(default=0)),
                ('totalexcludeamnt', models.FloatField(default=0)),
                ('inveid', models.IntegerField(blank=True, null=True)),
                ('invecode', models.CharField(blank=True, max_length=50, null=True)),
                ('invename', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('poinvid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.poinvhd')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listno', 'poinvid')},
            },
        ),
    ]
