# Generated by Django 3.1.1 on 2020-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0006_poinvdt_poinvhd'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='receivedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
